### ISSUE TITLE
General RuboCop offenses appear in problem list in VSCode 1.78.2

### ISSUE THREAD

**Issue by rbgrouleff** [standardrb/vscode-standard-ruby#11]
I am not entirely sure, this is related to the Standard extension, but I can't find anything else that somehow invokes RuboCop in VSCode.

After updating VSCode to v1.78.2, it seems like Standard has begun reporting RuboCop offenses like "Prefer single-quoted strings..." as well as Standard offenses like "Prefer double-quoted strings...".

The only Ruby related extensions, I have running, are Ruby LSP and Standard Ruby.

Standard is btw. autofixing the single quotes to double quotes, when saving.

VSCode version: 1.78.2
Ruby version: MRI 3.2.1
Standard version: 1.28.2
vscode-standard-ruby version: 0.0.15

The Ruby and Standard related VSCode settings, I have, are:

```json
"[ruby]": {
    "editor.defaultFormatter": "testdouble.vscode-standard-ruby"
  },
  "standardRuby.mode": "enableViaGemfile",
  "rubyLsp.formatter": "none",
  "rubyLsp.rubyVersionManager": "asdf",
  "rubyLsp.enabledFeatures": {
    "codeActions": true,
    "diagnostics": true,
    "documentHighlights": true,
    "documentLink": true,
    "documentSymbols": true,
    "foldingRanges": true,
    "formatting": true,
    "hover": true,
    "inlayHint": true,
    "onTypeFormatting": true,
    "selectionRanges": true,
    "semanticHighlighting": true,
    "completion": true,
    "codeLens": false
  }
```

The contents of my `.standard.yml` is:

```yaml
ruby_version: 2.7
```

Screenshots of the problem lists:

<img width="941" alt="Screenshot 2023-05-18 at 10 39 58" src="https://github.com/standardrb/vscode-standard-ruby/assets/60459/9e88448d-839a-448b-9b26-d921e4f5895b">
<img width="817" alt="Screenshot 2023-05-18 at 10 28 18" src="https://github.com/standardrb/vscode-standard-ruby/assets/60459/2562fdd5-7824-412a-b972-499238b63864">

**Comment by searls** [comment]
You probably want to set

```
rubyLsp.enabledFeatures": {
    "diagnostics": false
}
```

Since it only supports rubocop

**Comment by rbgrouleff** [comment]
That did the trick!

Thank you, and I'm sorry for bothering you with this 🙏
