### ISSUE TITLE
Add this extension to VSCodium

### ISSUE THREAD

**Issue by Adnilson** [standardrb/vscode-standard-ruby#14]
Hi,

My team started using standard and I personally use [VSCodium](https://vscodium.com/) (VSCode without proprietary binaries) with its own [OSS marketplace](https://open-vsx.org/).

Your extension is not there and I'd like to know if it is possible for you to publish it.

Here is the publishing [guide](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

Thanks!

**Comment by searls** [comment]
We don't have plans to publish the extension to any other registries but Microsoft's official one. You're welcome to pull down a release and install it manually, though.
